### ISSUE TITLE
Bug in step2.5 optimal_nmax.py

### ISSUE THREAD

**Issue by ArthurSilver** [nsmro/synphoni#1]
In line 94 m_ls = [x.stem for x in (folder / "Parahoxozoa").glob("*")]
It should be (folder / node) rather than (folder / "Parahoxozoa")

**Comment by nsmro** [comment]
Hi Arthur, thanks for pointing that out. Turns out I this version of the script wasn't the one I used for the paper (and still had this typo). It's now corrected.
